title: My docs
description: Setting up CI with my own project
permalink: pretty
search_enabled: true
color_scheme: dark

remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme